language: node_js
node_js:
 - "node"

cache: npm

before_script:
  - cd dapp
  - npm install

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dapp/dist
 on:
   branch: master
